Repository pacstall/pacstall, pull requests merged in 2021-10, with the labels that each got.

#270 fix(main): fixes #269
  pacstall
Labels: hacktoberfest-accepted

#268 feat(scripts): Ability to specify target repo when installing
  misc/scripts/search.sh
Labels: hacktoberfest-accepted

#272 fix(main): Code quality issues
  pacstall
Labels: hacktoberfest-accepted

#274 bugfix/pacscript storage with pacdeps
  misc/scripts/install-local.sh
Labels: hacktoberfest-accepted

#275 feat(api): Make `ask()` read from pipe
  install.sh
  pacstall
  uninstall.sh
Labels: enhancement, hacktoberfest-accepted

#271 ref(search): Rework
  misc/scripts/search.sh
  pacstall
Labels: hacktoberfest-accepted

#273 fix(scripts): fix clutter on download
  misc/scripts/upgrade.sh
Labels: bugfix, Hacktoberfest, hacktoberfest-accepted

#276 fix(scripts): Code quality issues
  misc/scripts/add-repo.sh
  misc/scripts/download.sh
  misc/scripts/error_log.sh
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
  misc/scripts/search.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
Labels: enhancement, bugfix, Hacktoberfest, hacktoberfest-accepted
