Repository pacstall/pacstall, pull requests merged in 2021-09, with the labels that each got.

#232 Fix code quality issues
  Pipfile
  Pipfile.lock
  api/__init__.py
  api/config.py
  api/message.py
  install.py
  src/pacstall.py
Labels: python

#238 rem(scripts): Remove redundant confirmations
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
Labels: enhancement

#237 fix(upgrade): `ver_compare` issue
  misc/scripts/upgrade.sh
Labels: bugfix

#239 fix(github): `CODEOWNERS` and `PULL_REQUEST_TEMPLATE`
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: documentation

#240 fix(CoC): Port it to markdown
  CODE_OF_CONDUCT.md
Labels: documentation

#243 fix(scripts): Redirect `cd` errors to `/dev/null`
  misc/scripts/install-local.sh
Labels: bugfix

#251 fix(install-local): Unset `pkgver` after install
  misc/scripts/install-local.sh
Labels: bugfix

#252 dpkg gives error when lt is quoted
  misc/scripts/upgrade.sh
Labels: bugfix

#256 feat(readme): Add matrix space link
  README.md
Labels: documentation

#261 fix(install-local): `dpkg-query` false positives
  misc/scripts/install-local.sh
Labels: bugfix

#249 Remove fakeroot
  install.sh
  misc/scripts/install-local.sh
Labels: remove

#265 fix(main): Remove excess padding in `-h`
  pacstall
Labels: bugfix

#264 feat(scripts): Add more checks to the check function
  misc/scripts/install-local.sh
Labels: enhancement, bugfix
