Repository pacstall/pacstall, pull requests merged in 2021-07, with the labels that each got.

#105 Feature/no removescript variable
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
Labels: enhancement

#106 Fix: /root is not /home/root
  pacstall
Labels: bug

#93 Feat: Added Alpha `.deb` support using `wget` and `awk`
  misc/scripts/install-local.sh
Labels: enhancement

#120 Feat: Multi-repo support
  install.sh
  misc/scripts/add-repo.sh
  misc/scripts/change-repo.sh
  misc/scripts/download.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/search.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement

#129 Hotfixes for v1.5.1
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/scripts/update.sh
  pacstall
Labels: enhancement, hotfix

#130 Hotfix/1.5.1
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/scripts/update.sh
  pacstall
Labels: hotfix

#134 Style: Retab and add vim modeline
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/scripts/add-repo.sh
  misc/scripts/download.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/remove.sh
  misc/scripts/search.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: style

#141 Rem: `website-images`
  website-images/A3275672-7DBD-495F-B214-8721CFE644F9.png
  website-images/README.md
  website-images/button.png
  website-images/ezgif.com-video-to-gif.gif
  website-images/pacstall.png
  website-images/pacstall_tree.png
  website-images/pacstallascii.txt
Labels: remove

#138 Chan: Use `axel` instead of `aria2c`, and async `wget`
  install.sh
  misc/scripts/download.sh
  misc/scripts/install-local.sh
  misc/scripts/update.sh
  pacstall
Labels: enhancement

#145 Fix: Pacstall not removing `.deb` packages
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
Labels: bug

#142 Chan: `CONTRIBUTING.md`
  CONTRIBUTING.md
  misc/scripts/install-local.sh
Labels: documentation, enhancement, help wanted

#148 Doc: Add pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#147 Doc: Add missing GPL boilerplate
  misc/scripts/query-info.sh
  misc/scripts/remove.sh
  misc/scripts/update.sh
Labels: documentation

#149 Fix: Move the pull request template outside
  .github/pull_request_template.md
Labels: bug, documentation

#146 Feat: Add bulk install with error logging
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/scripts/download.sh
  misc/scripts/error_log.sh
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
  misc/scripts/search.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement

#158 Fix(install): Use `awk` instead of `cut`
  misc/scripts/install-local.sh
Labels: enhancement

#151 Feat: moves optdepends to before building
  misc/scripts/install-local.sh
Labels: enhancement

#152 Feat: Add fakeroot
  install.sh
  misc/scripts/install-local.sh
Labels: enhancement

#161 Fix: Caching
  misc/scripts/download.sh
  pacstall
Labels: bug

#159 Feat: Error out when running pacstall as root
  pacstall
Labels: enhancement
