Repository pacstall/pacstall, pull requests merged in 2021-06, with the labels that each got.

#45 Add tree feature with `-T`
  install.sh
  pacstall
Labels: enhancement

#47 [bug] Remove CI testing on `push`
  .github/workflows/remote-bash.yml
Labels: bug

#49 [bug] Change job name of `issue-action` github action
  .github/workflows/labeler.yml
Labels: bug

#50 [Feature] Add stow install if not found
  misc/scripts/install-local.sh
  pacstall
Labels: enhancement

#53 [bug] Package should be removed if the grep matches
  misc/scripts/install-local.sh
Labels: bug

#57 [bug] Remove obsolete `rm`
  install.sh
Labels: bug

#58 License things
  README.md
Labels: documentation

#63 Add `-Il` flag to help menu
  pacstall
Labels: enhancement

#67 [enhancement] Improve Code quality
  CONTRIBUTING.md
  README.md
  install.sh
  misc/scripts/install-local.sh
  misc/scripts/upgrade.sh
Labels: enhancement, question

#72 Bugfix/noroot
  misc/scripts/download.sh
  misc/scripts/install-local.sh
  pacstall
Labels: enhancement

#74 Fix `-R` showing file error
  pacstall
Labels: bug

#76 Fix: Execute `trapc` with sudo privileges
  misc/scripts/install-local.sh
Labels: bug

#78 Fix: Phantom Updates
  misc/scripts/upgrade.sh
Labels: bug

#84 Fix Typo in docs
  docs/index.md
Labels: bug, documentation

#85 Feat: Cleanup
  install.sh
  misc/scripts/change-repo.sh
  misc/scripts/download.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/remove.sh
  misc/scripts/search.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement

#94 Feat: -Qi has color
  misc/scripts/query-info.sh
Labels: enhancement
