Repository pacstall/pacstall, pull requests merged in 2021-11, with the labels that each got.

#336 ref(pacstall): Rename msg on updating APT list
  src/pacstall.py
Labels: python, refactor

#341 feat(pacstall): Add argument parser
  src/pacstall.py
Labels: enhancement, python

#344 fix(pacstall): Code quality issues
  src/pacstall.py
Labels: python, bugfix

#351 feat(pacstall): Add locking mechanism
  src/pacstall.py
Labels: python

#330 feat(completions,install): Add missing `keep` features
  misc/completion/bash
  misc/completion/fish
  misc/scripts/install-local.sh
  pacstall
Labels: enhancement

#380 ref(src): Remove `scripts` directory
  src/scripts/add-repo.sh
  src/scripts/download.sh
  src/scripts/error_log.sh
  src/scripts/install-local.sh
  src/scripts/query-info.sh
  src/scripts/remove.sh
  src/scripts/search.sh
  src/scripts/update.sh
  src/scripts/upgrade.sh
Labels: python, refactor

#378 ref(poetry): `pipenv` -> `poetry`
  Pipfile
  Pipfile.lock
  pacstall/api/__init__.py
  pacstall/api/color.py
  pacstall/api/config.py
  pacstall/api/message.py
  pacstall/completion/bash
  pacstall/completion/fish
  pacstall/pacstall
  pacstall/scripts/add-repo.sh
  pacstall/scripts/download.sh
  pacstall/scripts/error_log.sh
  pacstall/scripts/install-local.sh
  pacstall/scripts/query-info.sh
  pacstall/scripts/remove.sh
  pacstall/scripts/search.sh
  pacstall/scripts/update.sh
  pacstall/scripts/upgrade.sh
  pacstall/uninstall.sh
  poetry.lock
  pyproject.toml
Labels: python, refactor

#381 feat(readme): Improve badges
  README.md
Labels: enhancement, python

#386 ref(codebase): Rebase `python3-rewrite` on it
  CODE_OF_CONDUCT.org
  Pipfile
  Pipfile.lock
  README.md
  install.sh
  pacstall.8.gz
  pacstall/api/__init__.py
  pacstall/api/color.py
  pacstall/api/config.py
  pacstall/api/message.py
  pacstall/completion/bash
  pacstall/completion/fish
  pacstall/pacstall.py
  poetry.lock
  pyproject.toml
  src/install.py
  src/pacstall
  src/scripts/add-repo.sh
  src/scripts/download.sh
  src/scripts/error_log.sh
  src/scripts/install-local.sh
  src/scripts/query-info.sh
  src/scripts/remove.sh
  src/scripts/search.sh
  src/scripts/update.sh
  src/scripts/upgrade.sh
  src/uninstall.sh
Labels: python, refactor

#387 feat(cmds): Add initial `download` command
  pacstall/cmds/__init__.py
  pacstall/cmds/download.py
  pacstall/pacstall.py
  poetry.lock
  pyproject.toml
  src/pacstall.py
Labels: enhancement, python

#395 fix(upgrade): fix tabbing on upgrade list
  misc/scripts/upgrade.sh
Labels: bug

#393 fix(install): add overwrite of metadata
  misc/scripts/install-local.sh
Labels: bug
