Repository pacstall/pacstall, pull requests merged in 2021-08, with the labels that each got.

#153 Feat: use virtual packages for better apt integration & implement $gives
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
  pacstall
Labels: enhancement

#163 Fix: `upgrade.sh` version check
  misc/scripts/upgrade.sh
Labels: bug

#183 Feat: Initial `install.sh` revamp
  install.sh
Labels: bug, enhancement

#187 Feat: Add `The FOSS Code of Conduct`
  CODE_OF_CONDUCT.org
Labels: documentation

#194 Feat: Add removal script
  uninstall.sh
Labels: enhancement

#192 Feat: Unset variables in `install-local.sh` cleanup
  misc/scripts/install-local.sh
Labels: enhancement

#191 Feat: Added argument splitter for grouped short options
  pacstall
Labels: enhancement

#210 Revert "dpkg ignore dependency "errors""
  misc/scripts/install-local.sh
Labels: bug

#211 Fix: #209
  misc/scripts/install-local.sh
Labels: bug

#214 rem(install-local): View question
  misc/scripts/install-local.sh
Labels: enhancement

#212 Create CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#215 feat: Download optimizations
  misc/scripts/download.sh
  pacstall
Labels: enhancement

#217 rem(readme): Unnecessary `sudo`s
  README.md
Labels: bug

#218 feat(contributing): Add `shellcheck` requirement
  CONTRIBUTING.md
Labels: documentation

#219 fix(uninstaller): Revamp
  uninstall.sh
Labels: bug, enhancement

#220 feat(readme): Add uninstall section
  README.md
Labels: documentation

#231 feat(api): Add config module
  api/config.py
Labels: python
