Repository pacstall/pacstall, pull requests merged in 2021-05, with the labels that each got.

#9 Fix Code Quality issues
  misc/completion/bash
  misc/scripts/install-local.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement

#6 Feature/bugfix
  misc/completion/bash
  pacstall
Labels: bug, enhancement

#25 Remove outdated info
  README.md
Labels: documentation, enhancement

#26 Fix bugs in the update code block
  pacstall
Labels: bug

#28 Fix showing blank dependencies when removing packages
  pacstall
Labels: bug

#31 [enhancement] Configure the Auto-Labeler, test drive 2
  .github/workflows/labeler.yml
Labels: enhancement

#36 [feature] Add filters to the labeler
  .github/workflows/labeler.yml
Labels: enhancement

#44 [bug] Remove `fzf` dependency
  install.sh
Labels: bug
