Repository pacstall/pacstall, pull requests merged in 2022-05, with the labels that each got.

#581 fix(uninstall): package uninstallation
  uninstall.sh
Labels: bug, bash

#585 fix(pacstall): write error messages to `stderr`
  pacstall
Labels: bug, bash

#543 fix: use `set -euo pipefail` for pacscript functions
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
Labels: enhancement, bash

#589 fix(pacstall): check gitlab on `check_url` failure
  pacstall
Labels: bug, bash

#590 chore(codeowners): add @NarutoXY back
  .github/CODEOWNERS
Labels: chore
