Repository pacstall/pacstall, pull requests merged in 2022-12, with the labels that each got.

#720 feat: add `epoch`
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, pacscript

#728 fix(pin): use gives first
  misc/scripts/install-local.sh
Labels: bug, release notes, bash

#721 feat: add logging to pacstall functions
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash

#737 chore(funding): delete overriding funding config
  .github/FUNDING.yml
Labels: chore

#740 fix(upgrade): take epoch into account
  misc/scripts/upgrade.sh
Labels: bug, bash

#742 fix(upgrade.sh): skip git packages if `0$version` equals `$remoteversion` without `0`
  misc/scripts/upgrade.sh
Labels: bug, release notes, bash

#729 feat(createdeb): use `xz` instead of `gzip`
  misc/scripts/install-local.sh
Labels: release notes, bash, performance

#739 fix(log): figure out what `gives` is based on Deb
  misc/scripts/install-local.sh
Labels: bug, release notes, bash

#746 fix(upgrade): place wait to prevent overwritten variables
  misc/scripts/upgrade.sh
Labels: bug, release notes, bash, high priority

#744 chore(pacstall): `3.0.2` -> `3.1.0`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#748 fix(pacdeps): mark pacdep as auto installed
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
Labels: bug, release notes, bash

#750 fix(clean_logdir): use exec
  misc/scripts/install-local.sh
Labels: bug, hotfix, release notes, bash

#751 chore(pacstall): `3.1.0` -> `3.1.1`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#753 fix(remove): remove instead of purge
  misc/scripts/remove.sh
Labels: release notes, bash

#754 fix(hashcheck): use exit instead of return
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#756 feat(build): add `PACSTALL_BUILD_CORES` variable
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, performance
