Repository pacstall/pacstall, pull requests merged in 2022-04, with the labels that each got.

#547 docs(readme): update logo url
  README.md
Labels: documentation, bash

#559 style: reformat with `shfmt -bn -ci -sr -s`
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/scripts/add-repo.sh
  misc/scripts/download.sh
  misc/scripts/error_log.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/remove.sh
  misc/scripts/search.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
  uninstall.sh
Labels: style, bash

#561 fix(pacstall): exit properly
  pacstall
Labels: bash

#562 refactor: add and run pre-commit hooks
  .github/workflows/workflow.sh
  .pre-commit-config.yaml
  README.md
  misc/scripts/install-local.sh
  misc/scripts/search.sh
  pacstall
Labels: refactor, bash

#563 build(pacstall) `1.7.2` -> `1.7.3`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#564 release: 1.7.3
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/workflows/workflow.sh
  .pre-commit-config.yaml
  README.md
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/pacstall.8.gz
  misc/scripts/add-repo.sh
  misc/scripts/download.sh
  misc/scripts/error_log.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/remove.sh
  misc/scripts/search.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
  uninstall.sh
Labels: bash

#566 fix: remove useless sudos
  misc/scripts/install-local.sh
  misc/scripts/upgrade.sh
Labels: bash

#572 rm(update.sh): remove wacked apt command
  misc/scripts/update.sh
Labels: bash

#575 feat(pacstall): spruce up help message
  pacstall
Labels: style, bash
