Repository pacstall/pacstall, pull requests merged in 2022-03, with the labels that each got.

#513 docs(readme): remove inaccurate package count and reword "auto updates"
  README.md
Labels: documentation

#503 refractor: differentiate between file existence and network errors
  misc/scripts/download.sh
  misc/scripts/install-local.sh
  misc/scripts/search.sh
  pacstall
Labels: release notes, bash

#522 fix: accept paths with `-Il` command
  pacstall
Labels: bash

#504 fix(search): fail out on no package
  misc/scripts/search.sh
Labels: release notes, bash

#524 fix(check_url): add http code 301 to permitted list
  pacstall
Labels: bash

#523 fix(install-local): skip `$breaks` check for `-deb` upgrades
  misc/scripts/install-local.sh
Labels: bash

#515 fix(logger): log to appropriate streams
  pacstall/api/logger.py
Labels: bug, python

#530 fix(install-local): download patches before downloading package
  misc/scripts/install-local.sh
Labels: bug, bash

#511 fix(install-local): force git clones on `-git`
  misc/scripts/install-local.sh
Labels: bug, bash

#535 fix: add guards to download and speed up url checking
  misc/scripts/download.sh
  misc/scripts/install-local.sh
  pacstall
Labels: bug, release notes, bash

#532 docs(readme): revamp
  README.md
Labels: documentation, python, refactor

#526 fix: allow multiple fields in gives
  misc/scripts/install-local.sh
Labels: bug, bash
