Repository pacstall/pacstall, pull requests merged in 2022-08, with the labels that each got.

#628 feat: add `fancy_message sub` for cleaner output
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
  pacstall
Labels: enhancement, release notes, bash

#630 feat(install-local): show pretty index of optdepends
  misc/scripts/install-local.sh
Labels: enhancement, style, release notes, bash

#633 refactor(upgrade): remove `awk`
  misc/scripts/upgrade.sh
Labels: refactor, bash, performance

#634 fix(install-local.sh): do not create random file `t`
  misc/scripts/install-local.sh
Labels: bug, release notes, bash

#631 feat(optdepends): add array selection
  misc/scripts/install-local.sh
  pacstall
Labels: enhancement, release notes, bash

#632 feat(upgrade.sh): Parallel package version comparison on upgrade
  misc/scripts/upgrade.sh
Labels: enhancement, release notes, bash
