Repository pacstall/pacstall, pull requests merged in 2022-02, with the labels that each got.

#489 perf: remove dependency on `aiofiles`
  pacstall/cmds/download.py
  poetry.lock
  pyproject.toml
Labels: performance

#491 fix(install-local): install dependencies from deb
  misc/scripts/install-local.sh
Labels: bug, bash

#494 fix: skip network checks on github actions
  install.sh
  misc/scripts/download.sh
  pacstall
Labels: bug

#493 build(pacstall): 1.7.1 -> 1.7.2
  misc/pacstall.8.gz
  pacstall
Labels: build

#496 fix: allow certain commands to run with root
  pacstall/__main__.py
  pacstall/api/logger.py
Labels: bug

#501 fix(query-info): frozen `-Qi` when deb contains no size variable
  misc/scripts/query-info.sh
Labels: bug, release notes, bash

#505 fix(remove): purge without user input
  misc/scripts/remove.sh
Labels: bug

#506 fix(install-local): allow apt to downgrade packages
  misc/scripts/install-local.sh
Labels: bug, bash

#500 fix(install): properly purge build dependencies
  misc/scripts/install-local.sh
Labels: bug, release notes, bash

#508 fix(install-local): error out if optdepends has no description
  misc/scripts/install-local.sh
Labels: bug, release notes, bash
