Repository pacstall/pacstall, pull requests merged in 2022-01, with the labels that each got.

#435 fix(search): error when the query contains `-`
  misc/scripts/search.sh
Labels: bug, bash

#432 fix: prevent dummy deb from upgrading
  misc/scripts/install-local.sh
  misc/scripts/remove.sh
Labels: bug, bash

#439 fix: miscellaneous possible bugs due to possible dashes in inputs
  misc/scripts/add-repo.sh
  misc/scripts/download.sh
  misc/scripts/search.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: bug, release notes, bash

#437 fix(remove): removal of unidentified packages
  misc/scripts/remove.sh
Labels: bug, release notes, bash

#444 fix(install): ambiguous error message when `$gives` contains multiple fields
  misc/scripts/install-local.sh
Labels: bug, bash

#445 fix(upgrade.sh): warning -> warn
  misc/scripts/upgrade.sh
Labels: bug

#453 fix(remove): incomplete removal of packages from apt's database
  misc/scripts/remove.sh
Labels: bug, bash

#456 chore: add `.gitignore`
  .gitignore
Labels: python, chore

#455 feat(main)!: only launch as root
  pacstall/__main__.py
  pacstall/api/error_codes.py
Labels: python, BREAKING CHANGE

#460 feat(update)!: prevent updating to an incompatible release
  pacstall
Labels: enhancement, release notes, bash, BREAKING CHANGE

#459 fix(install-local): skip hash check if not present
  misc/scripts/install-local.sh
Labels: bash

#461 docs(readme): add reddit and mastodon badges
  README.md
Labels: documentation

#462 feat: add network checks
  install.sh
  misc/scripts/update.sh
  pacstall
Labels: enhancement, release notes, bash

#452 build(poetry): add launcher script
  pacstall/__main__.py
  pacstall/api/message.py
  pacstall/cmds/download.py
  pyproject.toml
Labels: python, chore

#471 feat(api): rewrite
  pacstall/__main__.py
  pacstall/api/__init__.py
  pacstall/api/config.py
  pacstall/api/logger.py
  pacstall/api/message.py
  pacstall/api/prompt.py
  pacstall/cmds/download.py
Labels: enhancement

#473 build(poetry): update dependencies
  poetry.lock
Labels: dependencies

#475 feat(download): rewrite
  pacstall/__main__.py
  pacstall/cmds/download.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#477 build(poetry): remove unused dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies
