Repository pacstall/pacstall, pull requests merged in 2022-07, with the labels that each got.

#600 fix(install): faulty network check
  install.sh
  uninstall.sh
Labels: bug, bash

#613 fix(install-local): make pacdeps actually install
  misc/scripts/install-local.sh
Labels: bash

#599 fix((un)install): write error messages to `stderr`
  install.sh
Labels: bug

#601 feat!: support for local repos
  misc/scripts/add-repo.sh
  misc/scripts/download.sh
  misc/scripts/search.sh
  pacstall
Labels: enhancement, release notes, bash

#606 chore(pacstall) `1.7.3` -> `2.0.0`, updated manpage
  misc/pacstall.8.gz
  pacstall
Labels: enhancement, refactor, bash

#618 fix(remove): source pacscript before running removescript
  misc/scripts/remove.sh
Labels: hotfix
