Repository pacstall/pacstall, pull requests merged in 2023-03, with the labels that each got.

#817 style(pre-commit): use 4 space tabs
  .pre-commit-config.yaml
Labels: style

#815 feat(install-local): show package name at beginning and end
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash

#816 fix(upgrade): use `mktemp` to prevent easy injection
  misc/scripts/upgrade.sh
Labels: enhancement, release notes, bash, low priority

#818 feat(main): allow format `username:branch` for updates
  pacstall
Labels: enhancement, release notes, bash

#819 refactor(install-local): quote everything, remove sed command
  misc/scripts/install-local.sh
Labels: enhancement, refactor, release notes, bash, low priority

#820 fix(install-local): remove duplicate code, use `SRCDIR`
  misc/scripts/install-local.sh
Labels: release notes, cleanup, bash, low priority

#821 feat(hashcheck): show broken hashes
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, low priority

#824 fix(SRCDIR): create without sudo
  misc/scripts/install-local.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, release notes, cleanup, bash, medium priority

#825 fix(error_log): logs in `/var/log` should not be user writable
  misc/scripts/error_log.sh
Labels: release notes, bash, medium priority

#826 rm: useless `hash -r` run
  misc/scripts/install-local.sh
Labels: remove, release notes, cleanup, bash, low priority

#830 fix(error_log): append instead of overwrite
  misc/scripts/error_log.sh
Labels: bug, release notes, bash, low priority

#833 fix(pacdeps): remove with sudo
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#839 fix(pacdeps): pacdeps are implicit deps to parent package
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#838 feat(pacstall): add `PACSTALL_PAYLOAD` support
  misc/scripts/install-local.sh
  pacstall
Labels: enhancement, release notes, bash

#841 refactor: quote variables & use `mapfile` wherever possible
  misc/scripts/add-repo.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/search.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, release notes, cleanup, bash, performance

#842 feat: add `preinst` function
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, pacscript

#840 feat(update.sh): allow local updates
  misc/scripts/install-local.sh
  misc/scripts/update.sh
  pacstall
Labels: enhancement, release notes, bash

#843 fix(deps): explicitly chosen optdepends are Depends
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#844 perf(install-local): use cut instead of awk, use bash globs instead of grep
  misc/scripts/install-local.sh
Labels: release notes, bash, performance, improvement

#845 fix: localize as many vars as possible
  misc/scripts/error_log.sh
  misc/scripts/search.sh
  pacstall
Labels: release notes, cleanup, bash

#848 fix(CARCH): set before source
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#846 fix(pacdeps): also check if `deps` no exist
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#849 fix(select_options): only allow ranges from smallest to greatest
  pacstall
Labels: bug, release notes, bash, improvement, medium priority

#850 fix(select_options): ranges cannot go from num to num
  pacstall
Labels: bug, release notes, bash, low priority

#851 chore(pacstall): `3.8.1` -> `3.9.0`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#853 feat(pacscript): add `homepage` property
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
Labels: enhancement, release notes, bash, pacscript, improvement

#856 perf: remove `basename` command
  misc/scripts/download.sh
  pacstall
Labels: release notes, bash, performance, low priority

#854 perf(grep): remove grep cases for bash regex
  misc/scripts/install-local.sh
  misc/scripts/update.sh
  pacstall
Labels: enhancement, release notes, bash, performance, improvement, low priority

#858 chore(pacstall): `3.9.0` -> `3.10.0`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#855 feat(pacscript): add backup key
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, pacscript, improvement

#861 fix(select_options): make everything more explicit
  misc/scripts/install-local.sh
  pacstall
Labels: enhancement, release notes, bash, improvement, low priority
