Repository pacstall/pacstall, pull requests merged in 2023-02, with the labels that each got.

#786 feat(download): add `quiet-wget` for silent download (#786
  pacstall
Labels: enhancement, bash, low priority

#790 fix(cleanup): unset all variables during life of pacscript
  misc/scripts/install-local.sh
Labels: bug, release notes, bash

#796 fix(compare_remote_version): unset `pkgver` before checks
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, high priority

#795 fix(pacdeps): remove pacdep file after pass
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#794 perf(search): use native find replace
  misc/scripts/search.sh
Labels: enhancement, release notes, bash, performance, improvement

#798 chore(pacstall): `3.5.0` -> `3.6.0`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#800 hotfix(arch): use `all` instead of `any`, export CARCH always
  misc/scripts/install-local.sh
Labels: bug, hotfix, bash, high priority

#801 chore(pacstall): `3.6.0` -> `3.6.1`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#803 feat: add `NO_COLOR` support
  pacstall
Labels: enhancement, release notes, bash, low priority

#804 fix(arch): recommend `any` instead of `all`
  misc/scripts/install-local.sh
Labels: release notes, bash, pacscript, medium priority

#805 fix(cleanup): remove `/tmp/pacstall` on cleanup
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, low priority

#808 ref(search): replace grep+cut+awk with awk
  misc/scripts/search.sh
Labels: enhancement, refactor, release notes, bash, performance
