Repository pacstall/pacstall, pull requests merged in 2023-08, with the labels that each got.

#949 fix(pacstall): ask punctuation
  misc/scripts/install-local.sh
  misc/scripts/upgrade.sh
Labels: style, release notes, bash

#951 upd(pacstall): `3.15.0` -> `4.0.0`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#950 add(update): `4.0.0` script
  misc/scripts/update.sh
Labels: enhancement, release notes, bash, medium priority

#926 feat!(pacscript): convert variables to PACBUILD equivs
  install.sh
  misc/scripts/checks.sh
  misc/scripts/dep-tree.sh
  misc/scripts/install-local.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, refactor, release notes, bash, pacscript, improvement, BREAKING CHANGE

#954 fix(pin): include `provides[@]` in pinning
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, improvement, low priority

#953 fix(full_version): use old style for debs
  misc/scripts/install-local.sh
  misc/scripts/upgrade.sh
Labels: bug, release notes, bash, medium priority

#957 refactor(dep-tree): remove responsive output
  misc/scripts/dep-tree.sh
Labels: style, remove, refactor, release notes, bash, medium priority

#956 fix(upgrade): remove pre-4.0.0 git versions
  misc/scripts/upgrade.sh
Labels: bug, release notes, bash, high priority

#959 upd(pacstall): `4.0.0` -> `4.0.1`
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  misc/pacstall.8.gz
  pacstall
Labels: bash

#964 fix(install): makedepends are too fragile to just remove
  misc/scripts/install-local.sh
Labels: bug, enhancement, remove, release notes, bash, improvement, medium priority

#963 fix(makedeb): log `Build-Depends`
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, low priority

#961 feat(pacscript): add `mask` array
  misc/scripts/checks.sh
  misc/scripts/dep-tree.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/search.sh
  pacstall
Labels: enhancement, release notes, bash, pacscript

#968 upd(pacstall): `4.0.1` -> `4.1.0`
  pacstall
Labels: bash

#970 fix(getMasks): redirect pipe output
  pacstall
Labels: bug, release notes, bash

#973 fix(search.sh): use different variable name
  misc/scripts/search.sh
Labels: bug, release notes, bash, high priority

#974 upd(pacstall): `4.1.0` -> `4.1.1`
  misc/pacstall.8.gz
  pacstall
Labels: bash
