Repository pacstall/pacstall, pull requests merged in 2023-07, with the labels that each got.

#881 fix(PACSTALL_PAYLOAD): skip if pacdep
  misc/scripts/install-local.sh
  pacstall
Labels: bug, release notes, bash, medium priority

#933 refactor(date): replace subshell calls to `date` with `printf`
  misc/scripts/error_log.sh
  misc/scripts/install-local.sh
Labels: refactor, release notes, bash, performance, improvement, low priority

#934 feat(-Qi): add queries
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  pacstall
Labels: enhancement, release notes, bash, improvement

#935 feat(-B): download deb if is deb package
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, improvement

#937 perf(-Qi): use name references instead of subshells
  misc/scripts/query-info.sh
Labels: enhancement, release notes, bash, performance, improvement

#938 refactor(pacstall): inline `size_of_deb`
  pacstall
Labels: release notes, bash, performance, low priority

#939 fix(log): use `declare` to avoid possible string splitting
  misc/scripts/install-local.sh
Labels: refactor, release notes, bash, improvement, medium priority

#940 fix(logdir): split `LOGDIR` into `LOGDIR` and `METADIR`
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/scripts/dep-tree.sh
  misc/scripts/error_log.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/remove.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: release notes, bash, low priority

#943 fix(-L): hide no install error on non-interactive
  pacstall
Labels: bug, release notes, bash, medium priority

#942 fix(pacstall): add `FARCH` array
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, low priority

#946 fix(check_url): use fullname instead of appending `/packagelist`
  pacstall
Labels: bug, release notes, bash, low priority

#947 fix(deb): run preinst if pacstall has it
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#948 perf(prompt_optdepends): do not regen cache on every apt-cache run
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, performance, improvement
