Repository pacstall/pacstall, pull requests merged in 2023-06, with the labels that each got.

#916 fix(is_apt_package_installed): accurately check install status
  pacstall
Labels: bug, release notes, bash, medium priority

#919 fix(createdeb): allow top level files
  misc/scripts/install-local.sh
Labels: bug, release notes, bash, medium priority

#917 feat(install): add `package` func to replace `install`
  misc/scripts/install-local.sh
  pacstall
Labels: enhancement, release notes, bash, pacscript, improvement, medium priority

#918 feat(pacscript): add `DISTRO` variable
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, pacscript, improvement

#927 feat(pacstallrepo): remove `txt` suffix
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/scripts/add-repo.sh
  misc/scripts/search.sh
  pacstall
Labels: refactor, release notes, bash, performance

#929 feat(upgrade): implement dependency tree
  install.sh
  misc/scripts/dep-tree.sh
  misc/scripts/error_log.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, release notes, bash, medium priority

#930 upd(pacstall): `3.14.1` -> `3.15.0`
  misc/pacstall.8.gz
  pacstall
Labels: release notes, bash
