Repository pacstall/pacstall, pull requests merged in 2024-08, with the labels that each got.

#1201 feat(search.sh): keyword and info search
  misc/scripts/search.sh
  pacstall
Labels: enhancement, release notes, bash, improvement

#1204 fix(build.sh): dependency bleed
  misc/scripts/build.sh
Labels: hotfix, cleanup, bash

#1205 ref(update.sh,README.md): remove matrix link
  README.md
  misc/scripts/update.sh
Labels: documentation, bash

#1203 feat(repo): add aliases
  install.sh
  misc/completion/bash
  misc/completion/fish
  misc/man/pacstall.5
  misc/man/pacstall.8
  misc/scripts/add-repo.sh
  misc/scripts/build.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/manage-repo.sh
  misc/scripts/quality-assurance.sh
  misc/scripts/search.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
  uninstall.sh
Labels: documentation, enhancement, refactor, release notes, cleanup, bash, improvement

#1211 fix(package.sh): repair bad cleanup on local pacscripts
  misc/scripts/package.sh
Labels: hotfix, cleanup, bash

#1210 fix(manage-repo.sh): wrong stack usage
  misc/scripts/manage-repo.sh
Labels: hotfix, cleanup, bash

#1209 fix({fetch-sources,checks}.sh): cleanup namerefs
  misc/scripts/checks.sh
  misc/scripts/fetch-sources.sh
Labels: hotfix, cleanup, bash

#1212 fix(install.sh): mandir creation
  install.sh
Labels: hotfix, cleanup, bash

#1213 upd(pacstall): `5.4.0` -> `5.4.1`
  misc/man/pacstall.5
  misc/man/pacstall.8
  pacstall
Labels: bash

#1216 fix(fetch-sources.sh): handle `devuan` and `kali` properly
  misc/scripts/fetch-sources.sh
Labels: hotfix, bash

#1219 fix({install,update}.sh): linguas newline not space sep
  install.sh
  misc/scripts/update.sh
Labels: hotfix, cleanup, bash

#1222 fix(ask): allow for printf usage
  misc/scripts/add-repo.sh
  misc/scripts/package-base.sh
  misc/scripts/package.sh
  misc/scripts/search.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, bash, medium priority
