Repository pacstall/pacstall, pull requests merged in 2024-12, with the labels that each got.

#1276 fix(search.sh): rm weird stray printf thing
  misc/scripts/search.sh
Labels: cleanup, bash

#1274 ref(pacstall)!: do not allow update if dpkg installed
  misc/po/pacstall.pot
  pacstall
Labels: refactor, bash, BREAKING CHANGE

#1277 fix(build.sh): don't mark already installed optdeps as deps in build only mode
  misc/scripts/build.sh
Labels: cleanup, bash

#1275 fix(suggested_solution): use double dash as separator instead of "ZZZZ"
  pacstall
Labels: style, bash, low priority

#1285 perf: remove some awk instances in favor of variable substitution
  misc/scripts/package.sh
Labels: bash, performance, improvement

#1283 feat(package): show reinstall warning
  misc/po/pacstall.pot
  misc/scripts/package.sh
Labels: enhancement, release notes, bash, improvement, low priority

#1281 fix(fetch-sources.sh): extract-to oopsies
  misc/scripts/fetch-sources.sh
Labels: hotfix, cleanup, bash

#1294 fix(version-constraints): fix missing version checks for installed packages
  misc/scripts/version-constraints.sh
Labels: bug, hotfix, release notes, high priority

#1295 fix(build.sh): make all maintainers uploaders
  misc/scripts/build.sh
Labels: hotfix, bash

#1296 fix(build.sh): repair replaces removal logic
  misc/scripts/build.sh
Labels: hotfix, bash

#1293 fix(fetch-sources): use more natural language
  misc/po/pacstall.pot
  misc/scripts/fetch-sources.sh
Labels: style, bash, low priority

#1301 fix(build.sh): emergency fix
  misc/scripts/build.sh
Labels: bash, high priority
