Repository pacstall/pacstall, pull requests merged in 2024-07, with the labels that each got.

#1157 fix(fetch-sources.sh): fix stacktrace
  misc/scripts/fetch-sources.sh
Labels: hotfix, cleanup, bash

#1158 fix(build.sh): only aptitude search when :arch in name
  misc/scripts/build.sh
Labels: hotfix, cleanup, bash

#1161 fix(pacstall,quality-assurance.sh): repair echo pipes
  misc/scripts/quality-assurance.sh
  pacstall
Labels: hotfix, cleanup, bash

#1160 fix({build,version-constraints}.sh): exhaust dep searches before failing
  misc/scripts/build.sh
  misc/scripts/package.sh
  misc/scripts/version-constraints.sh
  pacstall
Labels: hotfix, cleanup, bash

#1159 refactor({install,uninstall,update}.sh): clean up with sanity
  install.sh
  misc/scripts/update.sh
  uninstall.sh
Labels: enhancement, style, refactor, cleanup, bash, improvement

#1162 fix(*): cleanup pins and dep files
  misc/scripts/build.sh
  misc/scripts/package-base.sh
  misc/scripts/remove.sh
  pacstall
Labels: hotfix, cleanup, bash

#1163 fix(update.sh): drop stacktrace
  misc/scripts/update.sh
Labels: hotfix, cleanup, bash

#1164 fix({install,update}.sh): provide remote spdx-licenses for debian
  install.sh
  misc/scripts/update.sh
Labels: hotfix, cleanup, bash

#1166 fix(stacktrace): use correct variable in check
  pacstall
Labels: bug, bash, medium priority

#1168 fix(install.sh): drop `check_url`
  install.sh
Labels: hotfix, cleanup, bash

#1167 feat: add `bugs` variable
  misc/scripts/build.sh
  misc/scripts/checks.sh
  pacstall
Labels: enhancement, release notes, bash, pacscript

#1169 fix(*): cleanup stuff
  misc/scripts/build.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/package-base.sh
  misc/scripts/package.sh
  misc/scripts/search.sh
  pacstall
  uninstall.sh
Labels: hotfix, cleanup, bash

#1170 fix({fetch-sources,package}.sh): decompress `.tar.bz`/`.tbz` without the `2`
  misc/scripts/fetch-sources.sh
  misc/scripts/package.sh
Labels: enhancement, hotfix, release notes, cleanup, bash, pacscript, improvement

#1171 fix(*): cleanup again
  misc/scripts/fetch-sources.sh
  misc/scripts/package.sh
  pacstall
Labels: hotfix, cleanup, bash

#1165 fix(build.sh): always log at least one `provides`
  misc/scripts/build.sh
Labels: enhancement, release notes, bash, improvement

#1174 fix(build.sh): only make `/tmp/pacstall-no-build` with `-K`
  misc/scripts/build.sh
Labels: hotfix, release notes, cleanup, bash

#1176 fix({srcinfo,package-base}.sh): add missing overrides and append arrays
  misc/scripts/package-base.sh
  misc/scripts/srcinfo.sh
  pacstall
Labels: hotfix, release notes, cleanup, bash

#1177 fix(package-base.sh): accept child calls for local pacscripts
  misc/scripts/package-base.sh
  pacstall
Labels: hotfix, release notes, cleanup, bash

#1180 fix(package.sh): fix mapping payload_arr
  misc/scripts/package.sh
Labels: hotfix, cleanup, bash

#1181 fix(srcinfo.sh): allow read for enhanced arrays
  misc/scripts/srcinfo.sh
Labels: hotfix, cleanup, bash

#1182 fix(build.sh): cleanup dep files immediately
  misc/scripts/build.sh
Labels: hotfix, cleanup, bash

#1183 fix(fetch-sources.sh): print builddeps like others
  misc/scripts/build.sh
  misc/scripts/fetch-sources.sh
  pacstall
Labels: hotfix, cleanup, bash

#1186 fix(fetch-sources.sh): fix typo in makedep check
  misc/scripts/fetch-sources.sh
Labels: hotfix, cleanup, bash

#1190 fix(srcinfo.sh): CARCH/AARCH replaces
  misc/scripts/srcinfo.sh
Labels: hotfix, cleanup, bash

#1192 fix(srcinfo.sh): parse `.` properly
  misc/scripts/srcinfo.sh
Labels: hotfix, cleanup, bash

#1198 fix(build.sh): log all relations with dep const
  misc/scripts/build.sh
Labels: hotfix, cleanup, bash

#1200 fix({checks,fetch-sources}.sh): quote for loop entries
  misc/scripts/checks.sh
  misc/scripts/fetch-sources.sh
Labels: hotfix, cleanup, bash

#1199 fix({package,build}.sh): re-order replaces removal
  misc/scripts/build.sh
  misc/scripts/package.sh
Labels: refactor, cleanup, bash
