Repository pacstall/pacstall, pull requests merged in 2024-05, with the labels that each got.

#1094 fix(build-local.sh): update `KEEP` for 5.0.0 dirs
  misc/scripts/build-local.sh
Labels: hotfix, cleanup, bash

#1093 fix(main): improve flag-aware lock
  pacstall
Labels: hotfix, cleanup, bash

#1110 upd(pacstall): `5.0.0` -> `5.0.1`
  misc/pacstall.8.gz
  pacstall
Labels: bash

#1118 feat(add-repo.sh): allow `-Rr`/`--remove-repo`
  misc/scripts/add-repo.sh
  pacstall
Labels: enhancement, release notes, bash

#1122 fix(checks.sh): fix debs with `source_DISTRO`
  misc/scripts/checks.sh
Labels: hotfix, release notes, bash

#1126 feat(*): allow arch-style architecture naming
  misc/scripts/bwrap.sh
  misc/scripts/checks.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/package.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, release notes, bash, pacscript, improvement

#1131 fix({fetch-sources,checks}.sh): override with enhanced source for `-deb` pkgs
  misc/scripts/checks.sh
  misc/scripts/fetch-sources.sh
Labels: hotfix, release notes, cleanup, bash, pacscript
