Repository pacstall/pacstall, pull requests merged in 2024-06, with the labels that each got.

#1133 fix(build.sh): name `.deb`s correctly
  misc/scripts/build.sh
Labels: enhancement, style, release notes, bash, improvement

#1135 fix(fetch-sources.sh): make git clones follow quiet rules
  misc/scripts/fetch-sources.sh
Labels: enhancement, release notes, cleanup, bash, improvement

#1134 feat(*): provide more `control` fields
  misc/scripts/build.sh
  misc/scripts/checks.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/package.sh
  pacstall
Labels: enhancement, refactor, release notes, bash, pacscript, improvement

#1136 feat(srcinfo.sh): parse remote `.SRCINFO` data over pacscripts
  install.sh
  misc/scripts/build.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/get-pacscript.sh
  misc/scripts/srcinfo.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, refactor, release notes, bash, pacscript, improvement

#1132 fix({fetch-sources,package}.sh): install builddeps as a dummy
  misc/scripts/fetch-sources.sh
  misc/scripts/package.sh
Labels: enhancement, release notes, bash, pacscript, improvement

#1137 fix({build,srcinfo}.sh): missed stuff
  misc/scripts/build.sh
  misc/scripts/srcinfo.sh
Labels: hotfix, cleanup, bash

#1139 feat(man): gzip manpage at install-time
  install.sh
  misc/pacstall.8
  misc/pacstall.8.gz
  misc/scripts/update.sh
Labels: enhancement, release notes, bash

#1147 fix(fetch-sources.sh): make sure builddeps always install and not build
  misc/scripts/fetch-sources.sh
Labels: hotfix, cleanup, bash

#1149 fix({fetch-sources,upgrade}.sh): don't `chown` with a group
  misc/scripts/fetch-sources.sh
  misc/scripts/upgrade.sh
Labels: hotfix, cleanup, bash

#1155 refactor(*): parse parent distro if exists
  install.sh
  misc/scripts/build.sh
  misc/scripts/bwrap.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/package.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
Labels: enhancement, style, refactor, release notes, bash, pacscript, improvement

#1153 feat(*): allow `pkgbase` splitting
  install.sh
  misc/scripts/build.sh
  misc/scripts/bwrap.sh
  misc/scripts/checks.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/package-base.sh
  misc/scripts/package.sh
  misc/scripts/query-info.sh
  misc/scripts/search.sh
  misc/scripts/srcinfo.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, release notes, bash, pacscript, improvement

#1156 refactor(*): `stacktrace` and safe `rm`s
  misc/scripts/add-repo.sh
  misc/scripts/build.sh
  misc/scripts/bwrap.sh
  misc/scripts/checks.sh
  misc/scripts/dep-tree.sh
  misc/scripts/error-log.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/get-pacscript.sh
  misc/scripts/package-base.sh
  misc/scripts/package.sh
  misc/scripts/quality-assurance.sh
  misc/scripts/query-info.sh
  misc/scripts/remove.sh
  misc/scripts/search.sh
  misc/scripts/srcinfo.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  misc/scripts/version-constraints.sh
  pacstall
Labels: enhancement, style, refactor, release notes, cleanup, bash, improvement
