Repository pacstall/pacstall, pull requests merged in 2024-09, with the labels that each got.

#1229 fix({build,fetch-sources,version-constraints}.sh): `all` checks
  misc/scripts/build.sh
  misc/scripts/fetch-sources.sh
  misc/scripts/version-constraints.sh
Labels: hotfix, cleanup, bash

#1230 fix(apt): use proper apt config locations
  install.sh
  pacstall
Labels: bug, release notes, bash, low priority

#1239 fix(bash): add zsh exception for mapfile
  misc/completion/bash
Labels: bug, release notes, bash, medium priority

#1246 fix(pacstall): bad cleanup glob
  pacstall
Labels: hotfix, cleanup, bash

#1245 fix(build.sh): repair dep else check
  misc/scripts/build.sh
Labels: hotfix, cleanup, bash

#1251 fix(fetch-sources.sh): annotated commit hashes
  misc/scripts/fetch-sources.sh
Labels: hotfix, cleanup, bash
