Repository pacstall/pacstall, pull requests merged in 2024-03, with the labels that each got.

#1017 chan!(*): `name` -> `pkgname`
  misc/scripts/build-local.sh
  misc/scripts/checks.sh
  misc/scripts/download-local.sh
  misc/scripts/install-local.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: release notes, bash, pacscript, BREAKING CHANGE

#1051 chan!(*): `url` -> `{test_,}source_url`, `homepage` -> `url`
  misc/scripts/build-local.sh
  misc/scripts/checks.sh
  misc/scripts/download-local.sh
  misc/scripts/install-local.sh
Labels: refactor, release notes, bash, pacscript, BREAKING CHANGE

#1053 chan!(*): `hash` -> `*sums`
  misc/scripts/checks.sh
  misc/scripts/download-local.sh
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, pacscript, improvement, BREAKING CHANGE

#1054 feat({build,install}-local.sh): add `conflicts` array
  misc/scripts/build-local.sh
  misc/scripts/checks.sh
  misc/scripts/install-local.sh
Labels: enhancement, release notes, bash, pacscript, improvement

#1055 feat({build,download}-local.sh: add `{pre,post}_upgrade`, `pre_remove`
  misc/scripts/build-local.sh
  misc/scripts/download-local.sh
Labels: enhancement, release notes, bash, pacscript, improvement

#1022 feat!(maintainer): turn into array
  misc/scripts/build-local.sh
  misc/scripts/checks.sh
Labels: enhancement, release notes, bash, pacscript, improvement, BREAKING CHANGE

#1059 chan!(download-local.sh): break out `srcdir` -> `srcdir` + `_archive`
  misc/scripts/build-local.sh
  misc/scripts/download-local.sh
  misc/scripts/install-local.sh
Labels: enhancement, refactor, release notes, bash, pacscript, improvement, BREAKING CHANGE

#1060 feat(download-local): add `nosubmodules` array option
  misc/scripts/build-local.sh
  misc/scripts/download-local.sh
Labels: enhancement, release notes, bash, pacscript, improvement

#1063 feat(*): add `license` array
  misc/scripts/build-local.sh
  misc/scripts/checks.sh
  misc/scripts/query-info.sh
Labels: enhancement, release notes, bash, pacscript, improvement

#1062 fix(*-local.sh)!: mark `pacdeps` as deps for `-deb` pacs
  misc/scripts/build-local.sh
  misc/scripts/download-local.sh
  misc/scripts/install-local.sh
  misc/scripts/query-info.sh
Labels: enhancement, release notes, bash, pacscript, improvement, BREAKING CHANGE

#1030 chan(install.sh): remove `-qq` from most `apt` invocations
  install.sh
Labels: enhancement, bash, improvement, low priority

#1064 fix(download-local.sh): be verbose about pacstall hooks for -debs
  misc/scripts/download-local.sh
Labels: enhancement, bash, improvement

#1021 feat(depends,makedepends,optdepends): add version constraints
  install.sh
  misc/scripts/build-local.sh
  misc/scripts/checks.sh
  misc/scripts/install-local.sh
  misc/scripts/update.sh
  misc/scripts/version-constraints.sh
Labels: enhancement, release notes, bash, pacscript, improvement
