Repository pacstall/pacstall, pull requests merged in 2025-03, with the labels that each got.

#1338 chan(package): exit 1 on CI incompat again
  misc/scripts/package.sh
Labels: enhancement, release notes, bash, improvement

#1336 chore(README): remove outdated warning to debs
  README.md
Labels: documentation

#1339 ref(*): allow local installs to be picked up by upgrade
  misc/po/pacstall.pot
  misc/scripts/build.sh
  misc/scripts/dep-tree.sh
  misc/scripts/query-info.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, refactor, bash, improvement

#1341 fix(*): respect TMPDIR override
  misc/po/pacstall.pot
  misc/scripts/bwrap.sh
  misc/scripts/package-base.sh
  misc/scripts/update.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: hotfix, cleanup, bash

#1345 fix(fetch-sources.sh): allow `-deb`s to downgrade
  misc/scripts/fetch-sources.sh
Labels: hotfix, bash

#1346 fix({package,query-info}.sh): provide pacstall ver
  misc/scripts/package.sh
  misc/scripts/query-info.sh
Labels: hotfix, bash
