Repository pacstall/pacstall, pull requests merged in 2025-02, with the labels that each got.

#1326 fix({package-base,srcinfo}.sh): give split pkgs access to extended arrays
  misc/scripts/package-base.sh
  misc/scripts/srcinfo.sh
Labels: hotfix, bash

#1331 fix(search): fix origin url index of packages when masking packages
  misc/scripts/search.sh
Labels: hotfix, bash

#1333 fix({fetch-sources,package}.sh): allow `dest` to define extr when `source` doesn't
  misc/scripts/fetch-sources.sh
  misc/scripts/package.sh
Labels: hotfix, bash

#1332 fix({srcinfo,upgrade}.sh): repair split pkg upgrades
  misc/scripts/srcinfo.sh
  misc/scripts/upgrade.sh
  pacstall
Labels: hotfix, bash, high priority

#1334 feat(pacstall): allow env to define TMPDIR
  pacstall
Labels: enhancement, bash, improvement

#1312 feat(upgrade.sh): add list only option
  misc/scripts/upgrade.sh
  pacstall
Labels: enhancement, bash, improvement, low priority
